apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 878407416515.dkr.ecr.us-east-2.amazonaws.com/demo-frontend
  newName: 878407416515.dkr.ecr.us-east-2.amazonaws.com/demo-frontend
  newTag: 60b628f9
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
